mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'poll/', include('polls.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

mysite/polls/urls.py
from django.conf.urls import url

from .views import QuestionListView
from .views import QuestionDetailView

app_name = 'polls'

urlpatterns = [
    url(r'^$', QuestionListView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/?$', QuestionDetailView.as_view(), name="details"),
]

mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Question
from django.views.generic import ListView
from django.views.generic import DetailView


class QuestionListView(ListView):
    template_name = 'polls/index.html'

    def get_queryset(self):
        return Question.objects.all()


def question_list_view(request):
    results = Question.objects.all()
    return render(request, 'polls/index.html', {'question_list':
                                                results})


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'polls/detail.html'


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if question.choice_set.all %}
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>
{% else %}
    
    <strong>No choices yet!</strong>

{% endif%}

mysite/polls/templates/polls/index.html
<h1>Polls Listing</h1>
{% if question_list %}
    <ul>
    {% for question in question_list %}
        
    <li>
        <a href="{% url 'polls:details' question.id %}">
            {{question.question_text}}
        </a>
    </li>
        
    {% endfor %}
    </ul>

{% else %}
    <strong>No Polls Yet!</strong>
{% endif %}